// <auto-generated />
using System;
using BudgetR.Simplified.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BudgetR.Simplified.Infrastructure.Data.Migrations
{
    [DbContext(typeof(BudgetRDbContext))]
    [Migration("20240902222507_AddMonthYears")]
    partial class AddMonthYears
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.7.24405.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BudgetR.Simplified.Domain.Entities.BusinessTransactionActivity", b =>
                {
                    b.Property<long>("BusinessTransactionActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BusinessTransactionActivityId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(2);

                    b.Property<string>("ProcessName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1);

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(3);

                    b.HasKey("BusinessTransactionActivityId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("BusinessTransactionActivities");

                    b.HasData(
                        new
                        {
                            BusinessTransactionActivityId = 1L,
                            CreatedAt = new DateTime(2024, 9, 2, 16, 25, 7, 306, DateTimeKind.Local).AddTicks(7038),
                            ProcessName = "Initial Seeding",
                            UserId = 1L
                        });
                });

            modelBuilder.Entity("BudgetR.Simplified.Domain.Entities.MonthYear", b =>
                {
                    b.Property<long>("MonthYearId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MonthYearId"));

                    b.Property<long?>("BusinessTransactionActivityId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnOrder(3);

                    b.Property<int>("Month")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("NumberOfDays")
                        .HasColumnType("int")
                        .HasColumnOrder(4);

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.HasKey("MonthYearId");

                    b.HasIndex("BusinessTransactionActivityId");

                    b.ToTable("MonthYears", (string)null);

                    b.HasData(
                        new
                        {
                            MonthYearId = 1L,
                            IsActive = true,
                            Month = 1,
                            NumberOfDays = 31,
                            Year = 2020
                        },
                        new
                        {
                            MonthYearId = 2L,
                            IsActive = true,
                            Month = 2,
                            NumberOfDays = 29,
                            Year = 2020
                        },
                        new
                        {
                            MonthYearId = 3L,
                            IsActive = true,
                            Month = 3,
                            NumberOfDays = 31,
                            Year = 2020
                        },
                        new
                        {
                            MonthYearId = 4L,
                            IsActive = true,
                            Month = 4,
                            NumberOfDays = 30,
                            Year = 2020
                        },
                        new
                        {
                            MonthYearId = 5L,
                            IsActive = true,
                            Month = 5,
                            NumberOfDays = 31,
                            Year = 2020
                        },
                        new
                        {
                            MonthYearId = 6L,
                            IsActive = true,
                            Month = 6,
                            NumberOfDays = 30,
                            Year = 2020
                        },
                        new
                        {
                            MonthYearId = 7L,
                            IsActive = true,
                            Month = 7,
                            NumberOfDays = 31,
                            Year = 2020
                        },
                        new
                        {
                            MonthYearId = 8L,
                            IsActive = true,
                            Month = 8,
                            NumberOfDays = 31,
                            Year = 2020
                        },
                        new
                        {
                            MonthYearId = 9L,
                            IsActive = true,
                            Month = 9,
                            NumberOfDays = 30,
                            Year = 2020
                        },
                        new
                        {
                            MonthYearId = 10L,
                            IsActive = true,
                            Month = 10,
                            NumberOfDays = 31,
                            Year = 2020
                        },
                        new
                        {
                            MonthYearId = 11L,
                            IsActive = true,
                            Month = 11,
                            NumberOfDays = 30,
                            Year = 2020
                        },
                        new
                        {
                            MonthYearId = 12L,
                            IsActive = true,
                            Month = 12,
                            NumberOfDays = 31,
                            Year = 2020
                        },
                        new
                        {
                            MonthYearId = 13L,
                            IsActive = true,
                            Month = 1,
                            NumberOfDays = 31,
                            Year = 2021
                        },
                        new
                        {
                            MonthYearId = 14L,
                            IsActive = true,
                            Month = 2,
                            NumberOfDays = 28,
                            Year = 2021
                        },
                        new
                        {
                            MonthYearId = 15L,
                            IsActive = true,
                            Month = 3,
                            NumberOfDays = 31,
                            Year = 2021
                        },
                        new
                        {
                            MonthYearId = 16L,
                            IsActive = true,
                            Month = 4,
                            NumberOfDays = 30,
                            Year = 2021
                        },
                        new
                        {
                            MonthYearId = 17L,
                            IsActive = true,
                            Month = 5,
                            NumberOfDays = 31,
                            Year = 2021
                        },
                        new
                        {
                            MonthYearId = 18L,
                            IsActive = true,
                            Month = 6,
                            NumberOfDays = 30,
                            Year = 2021
                        },
                        new
                        {
                            MonthYearId = 19L,
                            IsActive = true,
                            Month = 7,
                            NumberOfDays = 31,
                            Year = 2021
                        },
                        new
                        {
                            MonthYearId = 20L,
                            IsActive = true,
                            Month = 8,
                            NumberOfDays = 31,
                            Year = 2021
                        },
                        new
                        {
                            MonthYearId = 21L,
                            IsActive = true,
                            Month = 9,
                            NumberOfDays = 30,
                            Year = 2021
                        },
                        new
                        {
                            MonthYearId = 22L,
                            IsActive = true,
                            Month = 10,
                            NumberOfDays = 31,
                            Year = 2021
                        },
                        new
                        {
                            MonthYearId = 23L,
                            IsActive = true,
                            Month = 11,
                            NumberOfDays = 30,
                            Year = 2021
                        },
                        new
                        {
                            MonthYearId = 24L,
                            IsActive = true,
                            Month = 12,
                            NumberOfDays = 31,
                            Year = 2021
                        },
                        new
                        {
                            MonthYearId = 25L,
                            IsActive = true,
                            Month = 1,
                            NumberOfDays = 31,
                            Year = 2022
                        },
                        new
                        {
                            MonthYearId = 26L,
                            IsActive = true,
                            Month = 2,
                            NumberOfDays = 28,
                            Year = 2022
                        },
                        new
                        {
                            MonthYearId = 27L,
                            IsActive = true,
                            Month = 3,
                            NumberOfDays = 31,
                            Year = 2022
                        },
                        new
                        {
                            MonthYearId = 28L,
                            IsActive = true,
                            Month = 4,
                            NumberOfDays = 30,
                            Year = 2022
                        },
                        new
                        {
                            MonthYearId = 29L,
                            IsActive = true,
                            Month = 5,
                            NumberOfDays = 31,
                            Year = 2022
                        },
                        new
                        {
                            MonthYearId = 30L,
                            IsActive = true,
                            Month = 6,
                            NumberOfDays = 30,
                            Year = 2022
                        },
                        new
                        {
                            MonthYearId = 31L,
                            IsActive = true,
                            Month = 7,
                            NumberOfDays = 31,
                            Year = 2022
                        },
                        new
                        {
                            MonthYearId = 32L,
                            IsActive = true,
                            Month = 8,
                            NumberOfDays = 31,
                            Year = 2022
                        },
                        new
                        {
                            MonthYearId = 33L,
                            IsActive = true,
                            Month = 9,
                            NumberOfDays = 30,
                            Year = 2022
                        },
                        new
                        {
                            MonthYearId = 34L,
                            IsActive = true,
                            Month = 10,
                            NumberOfDays = 31,
                            Year = 2022
                        },
                        new
                        {
                            MonthYearId = 35L,
                            IsActive = true,
                            Month = 11,
                            NumberOfDays = 30,
                            Year = 2022
                        },
                        new
                        {
                            MonthYearId = 36L,
                            IsActive = true,
                            Month = 12,
                            NumberOfDays = 31,
                            Year = 2022
                        },
                        new
                        {
                            MonthYearId = 37L,
                            IsActive = true,
                            Month = 1,
                            NumberOfDays = 31,
                            Year = 2023
                        },
                        new
                        {
                            MonthYearId = 38L,
                            IsActive = true,
                            Month = 2,
                            NumberOfDays = 28,
                            Year = 2023
                        },
                        new
                        {
                            MonthYearId = 39L,
                            IsActive = true,
                            Month = 3,
                            NumberOfDays = 31,
                            Year = 2023
                        },
                        new
                        {
                            MonthYearId = 40L,
                            IsActive = true,
                            Month = 4,
                            NumberOfDays = 30,
                            Year = 2023
                        },
                        new
                        {
                            MonthYearId = 41L,
                            IsActive = true,
                            Month = 5,
                            NumberOfDays = 31,
                            Year = 2023
                        },
                        new
                        {
                            MonthYearId = 42L,
                            IsActive = true,
                            Month = 6,
                            NumberOfDays = 30,
                            Year = 2023
                        },
                        new
                        {
                            MonthYearId = 43L,
                            IsActive = true,
                            Month = 7,
                            NumberOfDays = 31,
                            Year = 2023
                        },
                        new
                        {
                            MonthYearId = 44L,
                            IsActive = true,
                            Month = 8,
                            NumberOfDays = 31,
                            Year = 2023
                        },
                        new
                        {
                            MonthYearId = 45L,
                            IsActive = true,
                            Month = 9,
                            NumberOfDays = 30,
                            Year = 2023
                        },
                        new
                        {
                            MonthYearId = 46L,
                            IsActive = true,
                            Month = 10,
                            NumberOfDays = 31,
                            Year = 2023
                        },
                        new
                        {
                            MonthYearId = 47L,
                            IsActive = true,
                            Month = 11,
                            NumberOfDays = 30,
                            Year = 2023
                        },
                        new
                        {
                            MonthYearId = 48L,
                            IsActive = true,
                            Month = 12,
                            NumberOfDays = 31,
                            Year = 2023
                        },
                        new
                        {
                            MonthYearId = 49L,
                            IsActive = true,
                            Month = 1,
                            NumberOfDays = 31,
                            Year = 2024
                        },
                        new
                        {
                            MonthYearId = 50L,
                            IsActive = true,
                            Month = 2,
                            NumberOfDays = 29,
                            Year = 2024
                        },
                        new
                        {
                            MonthYearId = 51L,
                            IsActive = true,
                            Month = 3,
                            NumberOfDays = 31,
                            Year = 2024
                        },
                        new
                        {
                            MonthYearId = 52L,
                            IsActive = true,
                            Month = 4,
                            NumberOfDays = 30,
                            Year = 2024
                        },
                        new
                        {
                            MonthYearId = 53L,
                            IsActive = true,
                            Month = 5,
                            NumberOfDays = 31,
                            Year = 2024
                        },
                        new
                        {
                            MonthYearId = 54L,
                            IsActive = true,
                            Month = 6,
                            NumberOfDays = 30,
                            Year = 2024
                        },
                        new
                        {
                            MonthYearId = 55L,
                            IsActive = true,
                            Month = 7,
                            NumberOfDays = 31,
                            Year = 2024
                        },
                        new
                        {
                            MonthYearId = 56L,
                            IsActive = true,
                            Month = 8,
                            NumberOfDays = 31,
                            Year = 2024
                        },
                        new
                        {
                            MonthYearId = 57L,
                            IsActive = true,
                            Month = 9,
                            NumberOfDays = 30,
                            Year = 2024
                        },
                        new
                        {
                            MonthYearId = 58L,
                            IsActive = true,
                            Month = 10,
                            NumberOfDays = 31,
                            Year = 2024
                        },
                        new
                        {
                            MonthYearId = 59L,
                            IsActive = true,
                            Month = 11,
                            NumberOfDays = 30,
                            Year = 2024
                        },
                        new
                        {
                            MonthYearId = 60L,
                            IsActive = true,
                            Month = 12,
                            NumberOfDays = 31,
                            Year = 2024
                        },
                        new
                        {
                            MonthYearId = 61L,
                            IsActive = true,
                            Month = 1,
                            NumberOfDays = 31,
                            Year = 2025
                        },
                        new
                        {
                            MonthYearId = 62L,
                            IsActive = true,
                            Month = 2,
                            NumberOfDays = 28,
                            Year = 2025
                        },
                        new
                        {
                            MonthYearId = 63L,
                            IsActive = true,
                            Month = 3,
                            NumberOfDays = 31,
                            Year = 2025
                        },
                        new
                        {
                            MonthYearId = 64L,
                            IsActive = true,
                            Month = 4,
                            NumberOfDays = 30,
                            Year = 2025
                        },
                        new
                        {
                            MonthYearId = 65L,
                            IsActive = true,
                            Month = 5,
                            NumberOfDays = 31,
                            Year = 2025
                        },
                        new
                        {
                            MonthYearId = 66L,
                            IsActive = true,
                            Month = 6,
                            NumberOfDays = 30,
                            Year = 2025
                        },
                        new
                        {
                            MonthYearId = 67L,
                            IsActive = true,
                            Month = 7,
                            NumberOfDays = 31,
                            Year = 2025
                        },
                        new
                        {
                            MonthYearId = 68L,
                            IsActive = true,
                            Month = 8,
                            NumberOfDays = 31,
                            Year = 2025
                        },
                        new
                        {
                            MonthYearId = 69L,
                            IsActive = true,
                            Month = 9,
                            NumberOfDays = 30,
                            Year = 2025
                        },
                        new
                        {
                            MonthYearId = 70L,
                            IsActive = true,
                            Month = 10,
                            NumberOfDays = 31,
                            Year = 2025
                        },
                        new
                        {
                            MonthYearId = 71L,
                            IsActive = true,
                            Month = 11,
                            NumberOfDays = 30,
                            Year = 2025
                        },
                        new
                        {
                            MonthYearId = 72L,
                            IsActive = true,
                            Month = 12,
                            NumberOfDays = 31,
                            Year = 2025
                        },
                        new
                        {
                            MonthYearId = 73L,
                            IsActive = true,
                            Month = 1,
                            NumberOfDays = 31,
                            Year = 2026
                        },
                        new
                        {
                            MonthYearId = 74L,
                            IsActive = true,
                            Month = 2,
                            NumberOfDays = 28,
                            Year = 2026
                        },
                        new
                        {
                            MonthYearId = 75L,
                            IsActive = true,
                            Month = 3,
                            NumberOfDays = 31,
                            Year = 2026
                        },
                        new
                        {
                            MonthYearId = 76L,
                            IsActive = true,
                            Month = 4,
                            NumberOfDays = 30,
                            Year = 2026
                        },
                        new
                        {
                            MonthYearId = 77L,
                            IsActive = true,
                            Month = 5,
                            NumberOfDays = 31,
                            Year = 2026
                        },
                        new
                        {
                            MonthYearId = 78L,
                            IsActive = true,
                            Month = 6,
                            NumberOfDays = 30,
                            Year = 2026
                        },
                        new
                        {
                            MonthYearId = 79L,
                            IsActive = true,
                            Month = 7,
                            NumberOfDays = 31,
                            Year = 2026
                        },
                        new
                        {
                            MonthYearId = 80L,
                            IsActive = true,
                            Month = 8,
                            NumberOfDays = 31,
                            Year = 2026
                        },
                        new
                        {
                            MonthYearId = 81L,
                            IsActive = true,
                            Month = 9,
                            NumberOfDays = 30,
                            Year = 2026
                        },
                        new
                        {
                            MonthYearId = 82L,
                            IsActive = true,
                            Month = 10,
                            NumberOfDays = 31,
                            Year = 2026
                        },
                        new
                        {
                            MonthYearId = 83L,
                            IsActive = true,
                            Month = 11,
                            NumberOfDays = 30,
                            Year = 2026
                        },
                        new
                        {
                            MonthYearId = 84L,
                            IsActive = true,
                            Month = 12,
                            NumberOfDays = 31,
                            Year = 2026
                        },
                        new
                        {
                            MonthYearId = 85L,
                            IsActive = true,
                            Month = 1,
                            NumberOfDays = 31,
                            Year = 2027
                        },
                        new
                        {
                            MonthYearId = 86L,
                            IsActive = true,
                            Month = 2,
                            NumberOfDays = 28,
                            Year = 2027
                        },
                        new
                        {
                            MonthYearId = 87L,
                            IsActive = true,
                            Month = 3,
                            NumberOfDays = 31,
                            Year = 2027
                        },
                        new
                        {
                            MonthYearId = 88L,
                            IsActive = true,
                            Month = 4,
                            NumberOfDays = 30,
                            Year = 2027
                        },
                        new
                        {
                            MonthYearId = 89L,
                            IsActive = true,
                            Month = 5,
                            NumberOfDays = 31,
                            Year = 2027
                        },
                        new
                        {
                            MonthYearId = 90L,
                            IsActive = true,
                            Month = 6,
                            NumberOfDays = 30,
                            Year = 2027
                        },
                        new
                        {
                            MonthYearId = 91L,
                            IsActive = true,
                            Month = 7,
                            NumberOfDays = 31,
                            Year = 2027
                        },
                        new
                        {
                            MonthYearId = 92L,
                            IsActive = true,
                            Month = 8,
                            NumberOfDays = 31,
                            Year = 2027
                        },
                        new
                        {
                            MonthYearId = 93L,
                            IsActive = true,
                            Month = 9,
                            NumberOfDays = 30,
                            Year = 2027
                        },
                        new
                        {
                            MonthYearId = 94L,
                            IsActive = true,
                            Month = 10,
                            NumberOfDays = 31,
                            Year = 2027
                        },
                        new
                        {
                            MonthYearId = 95L,
                            IsActive = true,
                            Month = 11,
                            NumberOfDays = 30,
                            Year = 2027
                        },
                        new
                        {
                            MonthYearId = 96L,
                            IsActive = true,
                            Month = 12,
                            NumberOfDays = 31,
                            Year = 2027
                        },
                        new
                        {
                            MonthYearId = 97L,
                            IsActive = true,
                            Month = 1,
                            NumberOfDays = 31,
                            Year = 2028
                        },
                        new
                        {
                            MonthYearId = 98L,
                            IsActive = true,
                            Month = 2,
                            NumberOfDays = 29,
                            Year = 2028
                        },
                        new
                        {
                            MonthYearId = 99L,
                            IsActive = true,
                            Month = 3,
                            NumberOfDays = 31,
                            Year = 2028
                        },
                        new
                        {
                            MonthYearId = 100L,
                            IsActive = true,
                            Month = 4,
                            NumberOfDays = 30,
                            Year = 2028
                        },
                        new
                        {
                            MonthYearId = 101L,
                            IsActive = true,
                            Month = 5,
                            NumberOfDays = 31,
                            Year = 2028
                        },
                        new
                        {
                            MonthYearId = 102L,
                            IsActive = true,
                            Month = 6,
                            NumberOfDays = 30,
                            Year = 2028
                        },
                        new
                        {
                            MonthYearId = 103L,
                            IsActive = true,
                            Month = 7,
                            NumberOfDays = 31,
                            Year = 2028
                        },
                        new
                        {
                            MonthYearId = 104L,
                            IsActive = true,
                            Month = 8,
                            NumberOfDays = 31,
                            Year = 2028
                        },
                        new
                        {
                            MonthYearId = 105L,
                            IsActive = true,
                            Month = 9,
                            NumberOfDays = 30,
                            Year = 2028
                        },
                        new
                        {
                            MonthYearId = 106L,
                            IsActive = true,
                            Month = 10,
                            NumberOfDays = 31,
                            Year = 2028
                        },
                        new
                        {
                            MonthYearId = 107L,
                            IsActive = true,
                            Month = 11,
                            NumberOfDays = 30,
                            Year = 2028
                        },
                        new
                        {
                            MonthYearId = 108L,
                            IsActive = true,
                            Month = 12,
                            NumberOfDays = 31,
                            Year = 2028
                        },
                        new
                        {
                            MonthYearId = 109L,
                            IsActive = true,
                            Month = 1,
                            NumberOfDays = 31,
                            Year = 2029
                        },
                        new
                        {
                            MonthYearId = 110L,
                            IsActive = true,
                            Month = 2,
                            NumberOfDays = 28,
                            Year = 2029
                        },
                        new
                        {
                            MonthYearId = 111L,
                            IsActive = true,
                            Month = 3,
                            NumberOfDays = 31,
                            Year = 2029
                        },
                        new
                        {
                            MonthYearId = 112L,
                            IsActive = true,
                            Month = 4,
                            NumberOfDays = 30,
                            Year = 2029
                        },
                        new
                        {
                            MonthYearId = 113L,
                            IsActive = true,
                            Month = 5,
                            NumberOfDays = 31,
                            Year = 2029
                        },
                        new
                        {
                            MonthYearId = 114L,
                            IsActive = true,
                            Month = 6,
                            NumberOfDays = 30,
                            Year = 2029
                        },
                        new
                        {
                            MonthYearId = 115L,
                            IsActive = true,
                            Month = 7,
                            NumberOfDays = 31,
                            Year = 2029
                        },
                        new
                        {
                            MonthYearId = 116L,
                            IsActive = true,
                            Month = 8,
                            NumberOfDays = 31,
                            Year = 2029
                        },
                        new
                        {
                            MonthYearId = 117L,
                            IsActive = true,
                            Month = 9,
                            NumberOfDays = 30,
                            Year = 2029
                        },
                        new
                        {
                            MonthYearId = 118L,
                            IsActive = true,
                            Month = 10,
                            NumberOfDays = 31,
                            Year = 2029
                        },
                        new
                        {
                            MonthYearId = 119L,
                            IsActive = true,
                            Month = 11,
                            NumberOfDays = 30,
                            Year = 2029
                        },
                        new
                        {
                            MonthYearId = 120L,
                            IsActive = true,
                            Month = 12,
                            NumberOfDays = 31,
                            Year = 2029
                        });
                });

            modelBuilder.Entity("BudgetR.Simplified.Domain.Entities.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"));

                    b.Property<string>("AuthenticationId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1);

                    b.Property<long?>("BusinessTransactionActivityId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(7);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(2);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(3);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnOrder(6);

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(4);

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAt");

                    b.Property<int>("UserType")
                        .HasColumnType("int")
                        .HasColumnOrder(5);

                    b.HasKey("UserId");

                    b.ToTable("Users", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("UserHistory");
                                ttb
                                    .HasPeriodStart("CreatedAt")
                                    .HasColumnName("CreatedAt");
                                ttb
                                    .HasPeriodEnd("ModifiedAt")
                                    .HasColumnName("ModifiedAt");
                            }));

                    b.HasData(
                        new
                        {
                            UserId = 1L,
                            AuthenticationId = "",
                            BusinessTransactionActivityId = 1L,
                            FirstName = "System",
                            IsActive = false,
                            UserType = 0
                        });
                });

            modelBuilder.Entity("BudgetR.Simplified.Domain.Entities.BusinessTransactionActivity", b =>
                {
                    b.HasOne("BudgetR.Simplified.Domain.Entities.User", "User")
                        .WithOne("BusinessTransactionActivity")
                        .HasForeignKey("BudgetR.Simplified.Domain.Entities.BusinessTransactionActivity", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BudgetR.Simplified.Domain.Entities.MonthYear", b =>
                {
                    b.HasOne("BudgetR.Simplified.Domain.Entities.BusinessTransactionActivity", "BusinessTransactionActivity")
                        .WithMany()
                        .HasForeignKey("BusinessTransactionActivityId");

                    b.Navigation("BusinessTransactionActivity");
                });

            modelBuilder.Entity("BudgetR.Simplified.Domain.Entities.User", b =>
                {
                    b.Navigation("BusinessTransactionActivity");
                });
#pragma warning restore 612, 618
        }
    }
}
